package com.college.assetmanager.entity;

public enum EventType {
    ASSET_CREATED, ASSET_UPDATED, ASSET_DELETED,
    BORROW_REQUESTED, BORROW_APPROVED, BORROW_REJECTED, BORROW_RETURNED,
    ISSUE_REPORTED, ISSUE_ASSIGNED, ISSUE_RESOLVED,
    RESERVATION_CREATED, RESERVATION_CANCELLED
}
