spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false
spring.flyway.out-of-order=true
spring.flyway.locations=classpath:db/migration

app.frontend.url=${FRONTEND_URL:https://campusassetmanagement.vercel.app}
app.backend.url=${BACKEND_URL:http://localhost:8080}

# CORS configuration
FRONTEND_URL=${FRONTEND_URL:https://campusassetmanagement.vercel.app}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true